language: python
python:
- '3.6'
install:
- pip3 install -r requirements.txt
script:
- pip3 install -r requirements_test.txt
- flake8 .
notifications:
  slack:
    secure: HnPuqbDw+VI21/kaePSwLoIGnQFVlaaCmo94lSw1IbB1LrPGl7lP9gGKmxPh35HNSCZDAGNy1mA2njsUtmRUuMkoNTENwDY5LA1BCx4dJt3Tq5Ni2O1CPFFso/1KnP1OijV5YENvfBz1b7fDgTrSgNo2kxxIo+JlEuf5xwVSoZZcPRfsvuC/ISqVb3ktlyghhlQqySIl1PVMXQPUqIVLnEzX4R4HLyw5wVf/Zj0fbuzhkjiZVpRGmX40LIAgLqmcFDVZRX5CPHU+3aClzFWRJ65W2v1RIOgKAlSLlcocOb7DE2i70Lw7vVH4ROaXAvCQkcgjmkeqb4XeCBoQOCbr8Tjqss8PUjuGn3quEKHUWoScKAgfZajoJbVYDup2GBjhoeZ3uMw4Rn4UOnFx5suAU32h6VW2uXo3IosCYs4KV2DqKfGlGc0RmbWMYepnPFCaBWZveVxu1/rq8fxnWBjWJc15hyHRp8LtSz8Tk6GJDZmuc0lE+W82saGyWGumkTOW7/nsCcGNCGyLXg1sZrYRaqk3zjojgtXBjZpg2sKOacKcmM2Pjx0SoJNqxkP5b+UqlOr9GQlU6R4B4MriZTmqtKBldyPeRpMTpF/+io5Y/OfVk3Wb1SpHq5FDe7bZE1As5Mtnu0qHjj0T34JcjwMZZq+kMk9De/4ME2BDxhRoMOs=
sudo: false
