language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- pip install -r requirements_test.txt
- flake8 .
deploy:
  provider: heroku
  api_key:
    secure: PZb3BpIx9z/MbuxQiqxdYJVe91gVRo/w78222aRnHM90g3lX6zqUfAI1eQgG2Z6mMS8aL7uHV75Hsm6WWbdOAu3cU7zuSwjd9gvNNSV02G7lHcVexXSYfz7VsEumd8e7M0gfD8ppM87H4tRZXWx1lXDD0fo/oeUkNWpT4wKjXS540PJg4mPFh0b0VyPj166HvpZNSNpidZHmomtU5+G7CuxyVdaPHfRBSlVLmCE5FUnw3JqDKYbNoyfwNcX9uLsH9bKgZ+jAIrhSFTl2OQhWYKt5rtgn/LDDC5Mr2QtzQCAJfJkou0SGJMJRSSY3q9rZuld8INpGp+geT2irrM3lxKF4BsIvaVso2CTA1bECY4kinZD1bJ2n3d+XyilNlpbobq4PbWv/0rLI1DkpjKg+qiTUPzMyV/7MitK7TqIhO0g6WbXn8hRXS8298jGdp5LhgnNHeheqIDIyFRE71ifJPfnSSxSI3tUvrUu84xPh2cS/7lR7iDLX8ku4gjBlUpbap4lArk6VlQD05vlbiScdiG0MJv5nWiiVS/yrwkwgq7q+TOYQkdPoRUjj6/AtodKwMvqsWu8Tl9/OSbneyApIZxIewjnGvcjpK6iI1Iv95q+DviPaUkneqQp1aunzD+OiBFp9qHkonylWHH3blriYkv/WVlsED5pMb6ka9MEsVmQ=
  app:
    master: mash-geo-api
    develop: mash-geo-api-preview
  on:
    repo: MashSoftware/geo-api
sudo: false
